# Uncomment the next line to define a global platform for your project


target 'Recording' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  platform :ios, '9.0'

pod 'React', :path => '../node_modules/react-native/'
pod 'React-Core', :path => '../node_modules/react-native/React'
 pod 'React-DevSupport', :path => '../node_modules/react-native/React'
 pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
 pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
 pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
 pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'
 pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
 pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
 pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
 pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
 pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
 pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
 pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
 pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
 pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
 pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
 pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'

 pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
 pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'


pod 'Firebase/Core', '~>5.19.0'
pod 'Firebase/Auth', '~> 5.19.0'
pod 'Firebase/Messaging', '~> 5.19.0'
pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'
# pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
# pod 'react-native-calendar-events', :path => '../node_modules/react-native-calendar-events'
# pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'
# pod 'GoogleSignIn'
  # pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'


 pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'
pod 'ReactNativePayments', :podspec => "../node_modules/react-native-payments/ReactNativePayments.podspec"
pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'


end


