export default Strings = {
  SIGN_IN_WITH_NUMBER: "Sign In with Phone Number",
  ENTER_PHONE_NUMBER_DESC: "Enter your phone number to receive your one-time SMS access code.",
  TEXT_YOUR_PHONE: "YOUR PHONE",

  //  TEXT_COUNTRY_CODE: '+91', // For India
  //  TEXT_COUNTRY_LOCALE: 'en-IN',// For India

  TEXT_COUNTRY_CODE: '+1', // For USA
  // TEXT_COUNTRY_CODE: '+91', // For INDIA

  TEXT_COUNTRY_LOCALE: 'en-US', // For USA

  TEXT_CONTINUE: "Continue",
  TEXT_OTP: "Enter SMS Access Code",
  TEXT_OTP_DESC: "We have sent you access code\n Via SMS for mobile number verification.",
  TEXT_VERIFY: "Verify",
  TEXT_RESEND_OTP: "Resend Code",
  TEXT_NAME: "Name",
  TEXT_ADD_NOTES: "Add note",
  TEXT_CARD_NUMBER: "Card Number",
  TEXT_EXPIRY: "Expiry",
  TEXT_CVV: "CVV",
  TEXT_EMAIL: "Email",
  TEXT_INSTAGRAM: "Instagram User Id",
  TEXT_PHONE_NUMBER: "Phone Number",
  TEXT_YOU_DO: "What do you do?",
  TEXT_SEARCH_RADIUS: 'Search Radius :',
  TEXT_CREATE_PROFILE: "Create Profile",
  TEXT_SAVE: "Save",
  TEXT_PLACEHOLDER_NAME: "Jack Smith",
  TEXT_PLACEHOLDER_ENTER_NOTES: "Enter Notes",
  TEXT_PLACEHOLDER_CARD_NUMBER: "4444 4444 4444 4444",
  TEXT_PLACEHOLDER_EXPIRY: "MMYY",
  TEXT_PLACEHOLDER_CVV: "123",
  TEXT_PLACEHOLDER_NUMBER: "+16663335555",
  TEXT_PLACEHOLDER_EMAIL: "jacksmith@gmail.com",
  TEXT_PLACEHOLDER_INSTAGRAM: "instagram user id",
  TEXT_AUTH_KEY: "rStudiosQWR2ZW50cnVzX2NyZWF0ZWRCeV9LcmlzaGFuQG9mZnN1cmVpdC5jb20=",
  TEXT_SUBMIT: "Submit",
  TEXT_CANCEL: "Cancel",
  TEXT_LOGOUT: "Logout",
  TEXT_LOGIN: "Login",
  TEXT_OKAY: "Okay",
  TEXT_LOGOUT_ANOTHER: "Logout Another",
  TEXT_PREMIUM: 'PREMIUM',
  TEXT_VERIFIED: 'VERIFIED',
  TEXT_OPEN: 'Open',
  TEXT_CALL: 'Call',
  TEXT_BOOK: 'Book',
  TEXT_CLOSED: 'Closed',
  TEXT_REQUEST_BOOK: 'Request to Book',
  TEXT_CART: 'Cart',
  TEXT_ABOUT_STUDIO: 'ABOUT THIS STUDIO',
  TEXT_STUDIO_HOURS: 'STUDIO HOURS',
  TEXT_STUDIO_PRICE: 'STUDIO PRICE',
  TEXT_STUDIO_RULES: 'STUDIO RULES',
  TEXT_STUDIO_CONTACT_INFORMATION: 'CONTACT INFORMATION',
  TEXT_AMENETIES: 'AMENETIES',
  TEXT_FEATURED_EQUIPMENT: 'FEATURED EQUIPMENT',
  TEXT_CANCELLATION_POLICY: 'CANCELLATION POLICY',
  TEXT_BOOKING_HOURS: '12 hours',
  TEXT_HOURS: ' hours',
  TAB_HISTORY: 'History',
  TAB_UPCOMING: 'Upcoming',
  TEXT_NEW_RESERVATION: 'New Reservation',
  TEXT_BOOK_ROOM: 'Book this Room',
  TEXT_PER_SESSION: 'per session',
  TEXT_PRIVACY_POLICY: 'http://neighborhoodwatche.com/privacy.html',
  TEXT_TERMS_CONDITIONS: 'http://neighborhoodwatche.com/terms.html',
  TEXT_TERMS_SERVICE: 'I accept Terms of Service and Privacy Policy.',
  TEXT_TITLE_PRIVACY: 'Privacy Policy',
  TEXT_TITLE_TERMS: 'Terms of Service',
  TEXT_VIDEO: 'Video',
  TEXT_NO_DATA: 'No Data Found',
  TEXT_NO_BOOKING: 'No upcoming booking found',
  TEXT_NO_HISTORY: 'No history found',
  TEXT_NO_LOCATION: 'Neighborhood Watche would like to acces your location to provide you studios nearby you.',
  TEXT_NEIGHTBORHOOD_WANTS_TO_SERVE_YOU_BETTER: 'The neighborhood wants to serve you better. Please enter any special instructions you may have pertaining to your booking reservation.',
  TEXT_RESERVATION_NAME: 'For whom this booking is or any special instructions?',
  // TEXT_RESERVATION_NAME: 'Any notes or special instructions?',
  TEXT_PARKING_SPACE_QUESTION: 'Do you need a parking space?',
  TEXT_ENGINEER_QUESTION: 'Do you need an engineer?',
  TEXT_PARKING_SPACE_USER_NAME: 'Who is the parking space for?',
  TEXT_SPECIAL_INSTRUCTIONS: 'Special Instructions',
  TEXT_NOTES: "Notes : ",

  TEXT_GOV_ID: `Your room has been reserved. Since this is your first time booking, we need a Government Photo ID on file. Drivers License, Passport, Green Card, Military ID are all accepted forms of identification.`,
  TEXT_UPLOAD: `Upload`
};